### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bloodykean** [Voljega/ExoDOSConverter#125]
Found error when processing DOOM :
Traceback (most recent call last):
  File "exoconverter.py", line 69, in convertGames
  File "exoconverter.py", line 117, in __convertGame__
  File "exoconverter.py", line 141, in __copyGameDataToOutputDir__
IndexError: list index out of range

ExoDos v6
Something not right in this array?

**Comment by Voljega** [comment]
I'm unable to reproduce this in last version
