### ISSUE TITLE
Can't seem to build latest commit

### ISSUE THREAD

**Issue by birdybro** [Voljega/ExoDOSConverter#33]
Log from attempting to compile below, it seems to be successful:

```
C:\Users\aberu\Downloads\ExoDOSConverter-master\work>pyinstaller --icon=exodosicon.ico --clean -F main.py
72 INFO: PyInstaller: 4.0
72 INFO: Python: 3.8.5
72 INFO: Platform: Windows-10-10.0.19041-SP0
73 INFO: wrote C:\Users\aberu\Downloads\ExoDOSConverter-master\work\main.spec
76 INFO: UPX is not available.
76 INFO: Removing temporary files and cleaning cache in C:\Users\aberu\AppData\Roaming\pyinstaller
92 INFO: Extending PYTHONPATH with paths
['C:\\Users\\aberu\\Downloads\\ExoDOSConverter-master\\work',
 'C:\\Users\\aberu\\Downloads\\ExoDOSConverter-master\\work']
104 INFO: checking Analysis
105 INFO: Building Analysis because Analysis-00.toc is non existent
106 INFO: Initializing module dependency graph...
108 INFO: Caching module graph hooks...
124 INFO: Analyzing base_library.zip ...
2773 INFO: Processing pre-find module path hook distutils from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2775 INFO: distutils: retargeting to non-venv dir 'c:\\python38\\lib'
5558 INFO: Caching module dependency graph...
5684 INFO: running Analysis Analysis-00.toc
5688 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python38\python.exe
5814 INFO: Analyzing C:\Users\aberu\Downloads\ExoDOSConverter-master\work\main.py
6623 INFO: Processing module hooks...
6624 INFO: Loading module hook 'hook-distutils.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
6626 INFO: Loading module hook 'hook-encodings.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
6720 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
6833 INFO: Loading module hook 'hook-PIL.Image.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
7156 INFO: Loading module hook 'hook-PIL.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
7158 INFO: Import to be excluded not found: 'PyQt4'
7158 INFO: Excluding import 'PyQt5'
7160 INFO:   Removing import of PyQt5 from module PIL.ImageQt
7161 INFO: Excluding import 'tkinter'
7163 INFO:   Removing import of tkinter from module PIL.ImageTk
7163 INFO: Import to be excluded not found: 'PySide'
7163 INFO: Import to be excluded not found: 'FixTk'
7164 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
7165 INFO: Import to be excluded not found: 'FixTk'
7166 INFO: Excluding import 'tkinter'
7167 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
7168 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
7169 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
7170 INFO: Loading module hook 'hook-xml.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
7170 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
7320 INFO: checking Tree
7321 INFO: Building Tree because Tree-00.toc is non existent
7322 INFO: Building Tree Tree-00.toc
7383 INFO: checking Tree
7384 INFO: Building Tree because Tree-01.toc is non existent
7385 INFO: Building Tree Tree-01.toc
7421 INFO: Looking for ctypes DLLs
7453 INFO: Analyzing run-time hooks ...
7456 INFO: Including run-time hook 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
7458 INFO: Including run-time hook 'c:\\python38\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
7467 INFO: Looking for dynamic libraries
8022 INFO: Looking for eggs
8022 INFO: Using Python library c:\python38\python38.dll
8023 INFO: Found binding redirects:
[]
8028 INFO: Warnings written to C:\Users\aberu\Downloads\ExoDOSConverter-master\work\build\main\warn-main.txt
8098 INFO: Graph cross-reference written to C:\Users\aberu\Downloads\ExoDOSConverter-master\work\build\main\xref-main.html
8138 INFO: checking PYZ
8138 INFO: Building PYZ because PYZ-00.toc is non existent
8139 INFO: Building PYZ (ZlibArchive) C:\Users\aberu\Downloads\ExoDOSConverter-master\work\build\main\PYZ-00.pyz
8979 INFO: Building PYZ (ZlibArchive) C:\Users\aberu\Downloads\ExoDOSConverter-master\work\build\main\PYZ-00.pyz completed successfully.
8995 INFO: checking PKG
8995 INFO: Building PKG because PKG-00.toc is non existent
8995 INFO: Building PKG (CArchive) PKG-00.pkg
12245 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
12267 INFO: Bootloader c:\python38\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
12267 INFO: checking EXE
12267 INFO: Building EXE because EXE-00.toc is non existent
12268 INFO: Building EXE from EXE-00.toc
12269 INFO: Copying icons from ['exodosicon.ico']
12355 INFO: Writing RT_GROUP_ICON 0 resource with 20 bytes
12356 INFO: Writing RT_ICON 1 resource with 165640 bytes
12360 INFO: Updating manifest in C:\Users\aberu\Downloads\ExoDOSConverter-master\work\build\main\run.exe.xj47unal
12434 INFO: Updating resource type 24 name 1 language 0
12438 INFO: Appending archive to EXE C:\Users\aberu\Downloads\ExoDOSConverter-master\work\dist\main.exe
12520 INFO: Building EXE from EXE-00.toc completed successfully.
```

I checked the warn-main.txt since I noticed the error from it:

```
missing module named 'org.python' - imported by copy (optional), xml.sax (delayed, conditional)
missing module named _frozen_importlib_external - imported by importlib._bootstrap (delayed), importlib (optional), importlib.abc (optional), zipimport (top-level)
excluded module named _frozen_importlib - imported by importlib (optional), importlib.abc (optional), zipimport (top-level)
missing module named _posixshmem - imported by multiprocessing.resource_tracker (conditional), multiprocessing.shared_memory (conditional)
missing module named asyncio.DefaultEventLoopPolicy - imported by asyncio (delayed, conditional), asyncio.events (delayed, conditional)
missing module named termios - imported by tty (top-level), getpass (optional)
missing module named vms_lib - imported by platform (delayed, conditional, optional)
missing module named 'java.lang' - imported by platform (delayed, optional), xml.sax._exceptions (conditional)
missing module named java - imported by platform (delayed)
missing module named _winreg - imported by platform (delayed, optional)
missing module named readline - imported by cmd (delayed, conditional, optional), code (delayed, conditional, optional), pdb (delayed, optional)
missing module named org - imported by pickle (optional)
missing module named posix - imported by os (conditional, optional), shutil (conditional)
missing module named resource - imported by posix (top-level), test.support (optional)
missing module named grp - imported by shutil (optional), tarfile (optional), pathlib (delayed)
missing module named pwd - imported by posixpath (delayed, conditional), shutil (optional), tarfile (optional), pathlib (delayed, conditional, optional), http.server (delayed, optional), webbrowser (delayed), netrc (delayed, conditional), getpass (delayed), distutils.util (delayed, conditional, optional)
missing module named _scproxy - imported by urllib.request (conditional)
missing module named multiprocessing.get_context - imported by multiprocessing (top-level), multiprocessing.pool (top-level), multiprocessing.managers (top-level), multiprocessing.sharedctypes (top-level)
missing module named multiprocessing.TimeoutError - imported by multiprocessing (top-level), multiprocessing.pool (top-level)
missing module named multiprocessing.BufferTooShort - imported by multiprocessing (top-level), multiprocessing.connection (top-level)
missing module named multiprocessing.AuthenticationError - imported by multiprocessing (top-level), multiprocessing.connection (top-level)
missing module named win32evtlog - imported by logging.handlers (delayed, optional)
missing module named win32evtlogutil - imported by logging.handlers (delayed, optional)
missing module named _posixsubprocess - imported by subprocess (optional), multiprocessing.util (delayed)
missing module named multiprocessing.set_start_method - imported by multiprocessing (top-level), multiprocessing.spawn (top-level)
missing module named multiprocessing.get_start_method - imported by multiprocessing (top-level), multiprocessing.spawn (top-level)
missing module named olefile - imported by PIL.MicImagePlugin (top-level), PIL.FpxImagePlugin (top-level)
missing module named 'PySide2.QtGui' - imported by PIL.ImageQt (conditional, optional)
missing module named PySide2 - imported by PIL.ImageQt (conditional, optional)
missing module named 'PyQt5.QtGui' - imported by PIL.ImageQt (conditional, optional)
missing module named numpy - imported by PIL.ImageFilter (optional)
missing module named cffi - imported by PIL.Image (optional), PIL.PyAccess (optional), PIL.ImageTk (delayed, conditional, optional)
```

And when I try to launch the application:

```
C:\Users\aberu\Downloads\ExoDOSConverter-master\work>main.exe
eXoDOSConverter 0.7-beta
Script path : C:\Users\aberu\Downloads\ExoDOSConverter-master\work
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    gui = ExoGUI(scriptDir,logger, title)
  File "exogui.py", line 27, in __init__
    self.configuration = conf.loadConf(
  File "conf.py", line 9, in loadConf
    file = open(confFile,'r',encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aberu\\Downloads\\ExoDOSConverter-master\\work\\conf\\conf-exo.conf'
[32676] Failed to execute script main
```

There seems to be a problem in how the UNC path is handled, maybe.

**Comment by Voljega** [comment]
Well it seems it is built as you managed to launch it.

The issue is that the conf file is not found.
Maybe you forgot to do the last line of the build instructions and copy all the needed files and dirs in `C:\\Users\\aberu\\Downloads\\ExoDOSConverter-master\\work\\`?

**Comment by birdybro** [comment]
Ran all the way through it again, could have sworn I did it just right, but it works now. Thanks!
