### ISSUE TITLE
Exception thrown after processing for RetroPie

### ISSUE THREAD

**Issue by rimsky82** [Voljega/ExoDOSConverter#59]
```
Exception ignored in thread started by: <bound method ExoDOSConverter.convertGames of <exodosconverter.ExoDOSConverter object at 0x0000021FC1B20490>>
Traceback (most recent call last):
  File "exodosconverter.py", line 61, in convertGames
  File "metadatahandler.py", line 40, in writeXml
  File "xml\etree\ElementTree.py", line 1133, in tostring
  File "xml\etree\ElementTree.py", line 756, in write
  File "contextlib.py", line 113, in __enter__
  File "xml\etree\ElementTree.py", line 825, in _get_writer
  File "C:\Users\TybTyb\AppData\Local\Programs\Python\Python38\lib\encodings\__init__.py", line 98, in search_function
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1316, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1297, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 414, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 649, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 536, in _get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Joe\\AppData\\Local\\Temp\\_MEI194242\\base_library.zip'
```

This exception was thrown immediately after processing the 7200th game.  I don't see a gamelist.xml, so I'm assuming this error was fatal.  This took 8 hours, so I hope it doesn't start over on a second run?

**Comment by rimsky82** [comment]
Can confirm that a second try was successful without modification.  Thank you for checking for the existing output folder. :)

**Comment by Voljega** [comment]
Ok and the gamelist was regenerated the second tome ?
Not sure I handle that well...

Strange error though, seems an internal one from Python.

Shall I close the issue ?

**Comment by rimsky82** [comment]
There was no error the second time and the gamelist generated fine.  It's no longer an issue for me, whether it is for others on their first attempt I suppose would take some testing.  Whether or not you want to close the issue is up to you.

**Comment by Voljega** [comment]
Ok I'll close this one then
