### ISSUE TITLE
Error running the main exe

### ISSUE THREAD

**Issue by MikeS11** [Voljega/ExoDOSConverter#71]
Maybe I am doing something wrong but I am getting this error after I create the main.exe and try to run it in the main folder:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "exogui.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "util.py", line 5, in <module>
ModuleNotFoundError: No module named 'requests'
[29528] Failed to execute script main

**Comment by Voljega** [comment]
Hello,

So you managed to build the exe without errors but this happens when you run it right ?

That's strange, maybe try installing the requests module before building the exe ?
with `pip install requests` ?

Tell me if this helps.

**Comment by MikeS11** [comment]
Hmm same issue,

I do have python installed in this location:
C:\Users\Mike1\AppData\Local\Programs\Python\Python38
But i do have this path included in the windows environment path variable
including the scripts folder

**Comment by Voljega** [comment]
OK, not sure it would work just like that, did you managed to build this in the past or is it your first attempt ?

**Comment by MikeS11** [comment]
This my first attempt,

I installed python 3.8.X from the site provided but it conflicted with 3.9
installed from the windows store. After I removed 3.9 I was able to set the
path correctly in windows so 3.8 and its paths were forced to run.

So it should be using the correct version of python:

C:\Temp\Test2\ExoDOSConverter-master>python --version
Python 3.8.6

C:\Temp\Test2\ExoDOSConverter-master>pyinstaller --version
4.2

**Comment by MikeS11** [comment]
Building the main.exe works, running the main.exe does not.

**Comment by Voljega** [comment]
OK well that's strange .... I myself build with pyCharm and previously used Anaconda which was not very good.
I never building with only command line, seems in your case some dependencies are not included by pyInstaller...

I am also on 3.8
I must say I havent' try to build the latest commits though, so I should try that.... but at the moment I'm in the middle of a very heavy refactoring to properly handle the newly realeased eXoWin3x collection

**Comment by Voljega** [comment]
Hello @MikeS11, so I just built the latest version once again on Pycharm and have no issue.
I guess in your case, the linking during built process is not done correctly ?
You can try with Pycharm it's free

**Comment by MikeS11** [comment]
Thanks, I'll check it out and let you know.

Cheers

**Comment by Voljega** [comment]
Any update ? 
I know anohter user at the same issue on reddit and he manage to make it work by reinstalling a clean environment

**Comment by Voljega** [comment]
closed due to no activity
