### ISSUE TITLE
Latest build errors

### ISSUE THREAD

**Issue by Yopachi** [Voljega/ExoDOSConverter#82]
Maybe you can point me in the right direction. I'm having trouble generating an exe. Here is what it looks like:

G:\Downloads\ExoDOSConverter-9.1-beta>pyinstaller --icon=exodosicon.ico --clean -F main.py
508 INFO: PyInstaller: 4.3
508 INFO: Python: 3.9.5
523 INFO: Platform: Windows-10-10.0.19042-SP0
829 INFO: wrote G:\Downloads\ExoDOSConverter-9.1-beta\main.spec
1091 INFO: UPX is available.
1091 INFO: Removing temporary files and cleaning cache in C:\Users\Yopachi\AppData\Local\pyinstaller
1671 INFO: Extending PYTHONPATH with paths
['G:\\Downloads\\ExoDOSConverter-9.1-beta',
 'G:\\Downloads\\ExoDOSConverter-9.1-beta']
1758 INFO: checking Analysis
1759 INFO: Building Analysis because Analysis-00.toc is non existent
1759 INFO: Initializing module dependency graph...
1768 INFO: Caching module graph hooks...
1781 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
1796 INFO: Analyzing base_library.zip ...
5189 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\Yopachi\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
5196 INFO: distutils: retargeting to non-venv dir 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\\lib'
6913 INFO: Caching module dependency graph...
7213 INFO: running Analysis Analysis-00.toc
Traceback (most recent call last):
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\win32ctypes\pywin32\pywintypes.py", line 35, in pywin32error
    yield
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\win32ctypes\core\ctypes\_util.py", line 42, in check_null
    raise make_error(function, function_name)
OSError: [WinError 1920] The file cannot be accessed by the system.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\building\build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\building\build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "G:\Downloads\ExoDOSConverter-9.1-beta\main.spec", line 7, in <module>
    a = Analysis(['main.py'],
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\building\build_main.py", line 391, in assemble
    self.binaries.extend(bindepend.Dependencies([('', python, '')],
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\depend\bindepend.py", line 224, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\depend\bindepend.py", line 403, in getAssemblyFiles
    for assembly in getAssemblies(pth):
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\depend\bindepend.py", line 354, in getAssemblies
    res = GetManifestResources(pth)
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\utils\win32\winmanifest.py", line 1016, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyInstaller\utils\win32\winresource.py", line 170, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\win32ctypes\pywin32\win32api.py", line 43, in LoadLibraryEx
    return _dll._LoadLibraryEx(fileName, 0, flags)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Yopachi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (1920, 'LoadLibraryExW', 'The file cannot be accessed by the system.')

**Comment by Voljega** [comment]
Are you cag1984 ? ;) I fno, you seem to have the same problem as him, and it seems linked to moving his python3 installation files around.
Anyway, here's my full response on eXo's Discord :
`in general python installation is very touchy on windows, at one point in the development of exodos_converter, the whole python packages local installation corrupted itself
I tried to fix it manually and it was impossible, a labyrinth of errors, fixing one created three new errors !
I had to erase everything python related on my windows, then did a proper reinstallation of base python only, and i use pycharm to work on the project, it creates a virtual env which simplifies some things with packages (that's about all I understood) then I use the pyinstaller exclusively from inside pycharm terminal
ultimately I'm not doing anything manually with pip by myself, pycharm takes care of everything`

**Comment by Yopachi** [comment]
Nope, I'm new to the community. First time using python and I've installed it and uninstalled it a few different ways. Let me give pycharm a try and I'll report back here :)

**Comment by Voljega** [comment]
Ahah funny he had the exact same issues as you yesterday.
Hope it's not a python 3.9 issue ...

**Comment by Yopachi** [comment]
It might be a version 3.9 issue. I couldn't get it to work in the pycharm terminal. So I uninstalled 3.9 and installed python 3.8 and then followed the build.txt instructions and got my main.exe file.

**Comment by Voljega** [comment]
Thank you for investigating !
Well this is certainly not good, I'll open an issue for the 3.9 incompatibility
